### ISSUE TITLE
Generating Pro version login

### ISSUE THREAD

**Issue by jmanuel1609** [fomantic/create-fomantic-icons#15]
I tried to generate the Pro version  I set my token and doesnt work. I already had a private repository with the icons zip. and the unzip version 
this is the error. Can you help me please.
`  at createError (/Users/jesusroblejo/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jesusroblejo/.config/yarn/global/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/jesusroblejo/.config/yarn/global/node_modules/axios/lib/adapters/http.js:202:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`

**Comment by hammy2899** [comment]
@jmanuel1609 Are you a member of the FontAwesome Pro repository? https://github.com/FortAwesome/Font-Awesome-Pro

If you aren't you need to login [FontAwesome](https://fontawesome.com/sessions/sign-in) and link your GitHub account

![image](https://user-images.githubusercontent.com/11588822/60422222-74bdfb80-9be3-11e9-92b3-b97f4ecd3de1.png)

**Comment by hammy2899** [comment]
I'm going to guess this is fixed and close it.

If you have any problems feel free to reopen.
