### ISSUE TITLE
Problem with Pro version 5.9.0

### ISSUE THREAD

**Issue by lukaszs0** [fomantic/create-fomantic-icons#16]
I get following error with Pro version 5.9.0. Previous version work fine.
```
i asset doesn't exist locally, starting download
√ downloaded (fontawesome-pro-5.9.0-web.zip)
√ asset saved (C:\Users\User\AppData\Local\Temp\fui-icon-script\fontawesome-pro-5.9.0-web.zip)
√ asset extracted (C:\Users\User\AppData\Local\Temp\fui-icon-script\fontawesome-pro-5.9.0-web)
 - parsing iconsC:\Users\User\AppData\Roaming\npm-cache\_npx\10696\node_modules\create-fomantic-icons\lib\parsers\FontAwesome.js:53
                                searchTerms: iconMeta.search.terms,
                                                             ^

TypeError: Cannot read property 'terms' of null
    at C:\Users\User\AppData\Roaming\npm-cache\_npx\10696\node_modules\create-fomantic-icons\lib\parsers\FontAwesome.js:53:62
    at Array.forEach (<anonymous>)
    at C:\Users\User\AppData\Roaming\npm-cache\_npx\10696\node_modules\create-fomantic-icons\lib\parsers\FontAwesome.js:44:27
    at C:\Users\User\AppData\Roaming\npm-cache\_npx\10696\node_modules\create-fomantic-icons\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by hammy2899** [comment]
I just did some digging and it seems to be an issue with FontAwesome, I have raised an issue however I will try and implement a fix tonight.
